-- Lets Production/Admin mark where each numbered Reference Sample line
-- should sit on a category's reference image (Main Template / Mata
-- Pelajaran-Klas) so the teacher-facing form can overlay the teacher's own
-- typed text live, on top of the picture, at roughly the same spot the
-- picture's own drawn circled numbers point to — see
-- src/components/ReferenceImagePositionEditor.jsx /
-- src/components/ReferenceImageOverlay.jsx.
--
-- Keyed by row NUMBER ("1".."5"), not by field identity — deliberately,
-- so it stays correct regardless of Mata Pelajaran/Klas's drag-reorder or
-- Main Template's "+ Add Reference Row" extra rows: position "3" always
-- means "whatever currently sits at the teacher's numbered row 3."
-- Shape: { "1": { "x": 12.5, "y": 30.0 }, "2": { ... } } — x/y are
-- percentages (0-100) of the image's own natural bounds. No font
-- size/color/alignment fields — Production only needs to confirm row
-- arrangement here, not a final-render preview (the real artwork is built
-- separately in Adobe Illustrator).
alter table public.catalog_reference_images add column if not exists text_positions jsonb;
